<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\lib\select2\ThemeBoostrap\.github\FUNDING.yml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fsm.Adapters.Persistence\Fsm.Adapters.Persistence.csproj" />
    <ProjectReference Include="..\Fsm.Application\Fsm.Application.csproj" />
  </ItemGroup>

</Project>
